language: cpp
compiler: clang

branches:
    only:
        - master

addons:
  apt:
    packages:
      - cmake
      - libxrandr-dev

matrix:
  include:
    - os: linux
      env:
    - os: osx
      env:
          
script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
